CREATE TABLE IF NOT EXISTS "wms_item" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "code" varchar(20) NOT NULL,
    "name" varchar(60) NOT NULL,
    "unit" varchar(20) DEFAULT NULL,
    "category_id" bigint NOT NULL,
    "brand_id" bigint DEFAULT NULL,
    "remark" varchar(255) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
) COMMENT 'WMS 商品表';

CREATE TABLE IF NOT EXISTS "wms_item_sku" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(255) NOT NULL,
    "item_id" bigint NOT NULL,
    "bar_code" varchar(64) DEFAULT NULL,
    "code" varchar(64) DEFAULT NULL,
    "length" decimal(24, 6) DEFAULT NULL,
    "width" decimal(24, 6) DEFAULT NULL,
    "height" decimal(24, 6) DEFAULT NULL,
    "gross_weight" decimal(24, 6) DEFAULT NULL,
    "net_weight" decimal(24, 6) DEFAULT NULL,
    "cost_price" decimal(24, 6) DEFAULT NULL,
    "selling_price" decimal(24, 6) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
) COMMENT 'WMS 商品 SKU 表';

CREATE TABLE IF NOT EXISTS "wms_inventory" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "sku_id" bigint NOT NULL,
    "warehouse_id" bigint NOT NULL,
    "area_id" bigint NOT NULL DEFAULT '0',
    "quantity" decimal(24, 6) NOT NULL DEFAULT '0',
    "remark" varchar(255) DEFAULT NULL,
    "creator" varchar(64) DEFAULT '',
    "create_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar(64) DEFAULT '',
    "update_time" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "tenant_id" bigint NOT NULL DEFAULT '0',
    PRIMARY KEY ("id")
) COMMENT 'WMS 库存表';
